Index/urls.py
from django.urls import path
from Index import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('film/<int:film_id>/', views.film_detail_view, name='film_detail'),
    path('allclubs', views.view_all_clubs, name='allclubs'),
    path('logout/', views.logout_view, name="logout"),
    path('test404/', views.error_404, name='test404'),
    path('bookings/', views.purchased_bookings, name='purchased_bookings'),
    path('profile/', views.profile, name='profile'),
    path('profile/delete-account/', views.delete_account, name='delete_account'),
    path('confirm_delete/<int:booking_id>/', views.confirm_delete, name='confirm_delete'),
    path('view-club-bookings/', views.viewclubbookings, name='view_club_bookings'),
    ]

handler404 = 'Index.views.error_404'

web_project/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("Authentication.urls")),
    path("cinmanager/", include("CinManager.urls")),
    path("index/", include("Index.urls")),
    path("bookings/", include("Bookings.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('Accounts.urls')),
]

handler404 = 'Index.views.error_404'
urlpatterns += staticfiles_urlpatterns()

CinManager/models.py
from django.db import models
from django.core.validators import MaxValueValidator
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.
class Film(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    age_rating = models.PositiveSmallIntegerField()
    duration = models.PositiveIntegerField()
    trailer_description = models.TextField()
    imageurl = models.CharField(max_length=1000)

class Screen(models.Model):
    id = models.AutoField(primary_key=True)
    number = models.PositiveIntegerField()
    capacity = models.PositiveIntegerField(validators=[MaxValueValidator(300)])

class Showing(models.Model):
    id = models.AutoField(primary_key=True)
    film = models.ForeignKey(Film, on_delete=models.DO_NOTHING)
    screen = models.ForeignKey(Screen, on_delete=models.DO_NOTHING)
    date = models.DateTimeField()
    bookedseats = models.IntegerField(default=0)

class Club(models.Model):
    id = models.AutoField(primary_key=True, unique=True)
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    contact_number = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    discount_rate = models.PositiveIntegerField(default=0)

class ClubRep(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)
    dateofbirth = models.DateField(default=datetime.now)
    club = models.OneToOneField(Club, on_delete=models.CASCADE)

web_project/templates/UWEFlix/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'UWEFlix/site.css' %}" />
    <!-- Add a link to a Bootstrap CSS file -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />

    {% if messages %}
        <div class="dropdown-messages">
            {% for message in messages %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        </div>
    {% endif %}


</head>

<body>
    <div class="container mt-4">
        {% block content %} {% endblock %}
        <hr />
        <footer>
            <p>|2022 - Samuel Parchao - ESD|</p>
        </footer>
    </div>

    <!-- Add a link to a Bootstrap JavaScript file -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <script>
        $(document).ready(function () {
            $(".alert").fadeTo(2000, 500).slideUp(500, function () {
                $(".alert").slideUp(500);
            });
        });
    </script>

</body>

</html>

web_project/templates/UWEFlix/club_list.html
{% extends "UWEFlix/layout.html" %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-4">List of Clubs & Accounts</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Address</th>
                <th>Contact Number</th>
                <th>Email</th>
                <th>Discount Rate</th>
                <th>Account</th>
            </tr>
        </thead>
        <tbody>
            {% for club in club_data %}
            <tr>
                <td>{{ club.club.name }}</td>
                <td>{{ club.club.address }}</td>
                <td>{{ club.club.contact_number }}</td>
                <td>{{ club.club.email }}</td>
                <td>{{ club.club.discount_rate }} % </td>
                <td>
                    {% if club.button_text == 'View Account' %}
                        <a class="btn btn-primary" href="{% url 'view_account' club_id=club.club.id %}">View Account</a>
                    {% else %}
                        <a class="btn btn-primary" href="{% url 'create_or_view_account' club_id=club.club.id %}">Create Account</a>
                    {% endif %}
                </td>                
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

web_project/templates/UWEFlix/createclub.html
{% extends 'UWEFlix/layout.html' %}

{% block content %}

<h1>Register Club</h1>
<form method="post" action="{% url 'createclub' %}">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_name">Club Name:</label>
        <input type="text" class="form-control" id="id_name" name="name" required>
    </div>
    <div class="form-group">
        <label for="id_address">Address:</label>
        <input type="text" class="form-control" id="id_address" name="address" required>
    </div>
    <div class="form-group">
        <label for="id_contact_number">Contact Number:</label>
        <input type="text" class="form-control" id="id_contact_number" name="contact_number" required>
    </div>
    <div class="form-group">
        <label for="id_discount_rate">Discount Rate:</label>
        <input type="number" min="0" max="100" class="form-control" id="id_discount_rate" name="discount_rate" required>
    </div>
    <h2>Register Club Rep</h2>
    <div class="form-group row">
        <div class="col-6">
            <label for="firstname">First Name</label>
            <input type="text" class="form-control" id="firstname" name="firstname" required>
        </div>
        <div class="col-6">
            <label for="surname">Surname</label>
            <input type="text" class="form-control" id="surname" name="surname" required>
        </div>
    </div>
    <div class="form-group">
        <label for="id_email">Email:</label>
        <input type="email" class="form-control" id="id_email" name="email" required>
    </div>
    <div class="form-group">
        <label for="id_dateofbirth">Date of Birth:</label>
        <input type="date" class="form-control" id="id_dateofbirth" name="dateofbirth" required>
    </div>
    <button type="submit" class="btn btn-primary">Register</button>
    <a class="btn btn-secondary" href="{% url 'home' %}">Cancel</a>
</form>

{% endblock %}

web_project/templates/UWEFlix/createscreen.html
{% extends "UWEFlix/layout.html" %}
{% load static %}

{% block content %}

<div class="container mt-5 d-flex justify-content-center">
    <div class="card p-4 mt-4 mb-4 w-50">
        <h1 class="text-center mb-4">Create a new Screen</h1>
        {% if messages %}
        <ul class="alert alert-danger">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <form method="post" action="{% url 'createscreen' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_number">Number:</label>
                <input type="text" name="number" id="id_number" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="id_capacity">Capacity:</label>
                <input type="text" name="capacity" id="id_capacity" class="form-control" required>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-primary">Create Screen</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

web_project/templates/UWEFlix/delete_request_list.html
{% extends 'UWEFlix/layout.html' %}

{% block content %}
<div class="container">
    <h1>Cancellation Requests</h1>
    {% if delete_requests %}
        <table class="table">
            <thead>
                <tr>
                    <th>User</th>
                    <th>Film</th>
                    <th>Showing Date</th>
                    <th>Adult Tickets</th>
                    <th>Student Tickets</th>
                    <th>Child Tickets</th>
                    <th>Price</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for delete_request in delete_requests %}
                    <tr>
                        <td>{{ delete_request.user }}</td>
                        <td>{{ delete_request.booking.showing.film.title }}</td>
                        <td>{{ delete_request.booking.showing.date }}</td>
                        <td>{{ delete_request.booking.adult_tickets }}</td>
                        <td>{{ delete_request.booking.student_tickets }}</td>
                        <td>{{ delete_request.booking.child_tickets }}</td>
                        <td>£{{ delete_request.booking.price }}</td>
                        <td>
                            <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#confirmModal" data-delete-request-id="{{ delete_request.id }}">Accept</button>
                            <a href="{% url 'deny_delete_request' delete_request.id %}" class="btn btn-danger">Deny</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No cancellation requests found.</p>
    {% endif %}
</div>

<!-- Confirmation Modal -->
<div class="modal fade" id="confirmModal" tabindex="-1" aria-labelledby="confirmModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmModalLabel">Confirmation</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to accept this cancellation request?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <a href="#" class="btn btn-success" id="acceptButton">Accept</a>
            </div>
        </div>
    </div>
</div>

<script>
    var acceptButton = document.getElementById('acceptButton');
    var modalConfirmButton = document.querySelector('#confirmModal .modal-footer #acceptButton');

    modalConfirmButton.addEventListener('click', function() {
        var deleteRequestId = modalConfirmButton.getAttribute('data-delete-request-id');
        var url = "{% url 'delete_request' 0 %}".replace('0', deleteRequestId);
        window.location.href = url;
    });

    $('#confirmModal').on('show.bs.modal', function(event) {
        var button = $(event.relatedTarget);
        var deleteRequestId = button.data('delete-request-id');
        acceptButton.setAttribute('data-delete-request-id', deleteRequestId);
    });
</script>
{% endblock %}

web_project/templates/UWEFlix/edit_payment_details.html
{% extends 'UWEFlix/layout.html' %}

{% block content %}
    <h2>Edit Payment Details</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ payment_details_form.account_number.id_for_label }}">Account Number:</label>
            {{ payment_details_form.account_number }}
        </div>
        <div class="form-group">
            <label for="{{ payment_details_form.cvv.id_for_label }}">CVV:</label>
            {{ payment_details_form.cvv }}
        </div>
        <div class="form-group">
            <label for="{{ payment_details_form.expdate.id_for_label }}">Expiration Date:</label>
            {{ payment_details_form.expdate }}
        </div>              
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
{% endblock %}

web_project/templates/UWEFlix/error_404.html
{% extends 'UWEFlix/base.html' %}

{% block content %}
<h1>404 Error</h1>
<p>The page you are looking for could not be found.</p>
{% endblock %}

web_project/templates/UWEFlix/home.html
{% extends "UWEFlix/layout.html" %}
{% load static %}

{% block content %}
{% if request.user.is_authenticated %}
{% with user=request.user %}

<div class="container mt-4">
    <h1>Welcome {{ user.first_name }}</h1>
    <h3>Here are the films currently on UWEFlix</h3>
    &nbsp;
    <form method="get">
        <label for="date">Filter by date:</label>
        <input type="date" id="date" name="date" value="{{ selected_date }}">
        <button type="submit">Apply Filter</button>
        <a href="{% url 'home' %}">Reset</a>
    </form>    
    &nbsp;
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="row">
        {% for film in films %}
        <div class="col-6">
            <div class="card mb-4">
                <div class="card-body">
                    <h5 class="card-title">{{ film.title }}</h5>
                    <img src="{{ film.imageurl }}" alt="{{ film.title }}" class="img-fluid" style="max-height: 200px">
                    <p class="card-text">
                        Age rating: {{ film.age_rating }}<br>
                        Duration: {{ film.duration }} minutes<br>
                        Description: {{ film.trailer_description }}
                    </p>
                    <a href="{% url 'film_detail' film.id %}?date={{ selected_date }}" class="btn btn-primary">Learn more</a>
                    {% if not film.has_showings and userpermissions == 1 %}
                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteFilmModal{{ film.id }}">Delete Film</button>
                    {% endif %}
                    {% if userpermissions == 1 %}
                    <a href="{% url 'update_film' film_id=film.id %}" class="btn btn-secondary">Edit Film</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="modal fade" id="deleteFilmModal{{ film.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteFilmModalLabel{{ film.id }}" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteFilmModalLabel{{ film.id }}">Delete Film</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Are you sure you want to delete the film "{{ film.title }}"?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <a href="{% url 'delete_film' film_id=film.id %}" class="btn btn-danger">Delete</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>
{% endwith %}
{% endif %}
{% endblock %}

web_project/templates/UWEFlix/payment.html
{% extends 'UWEFlix/layout.html' %}

{% block content %}
<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2>Complete Your Purchase</h2>
            <hr>
            <div id="stripe-payment-form"></div>
            <script src="https://js.stripe.com/v3/"></script>
            <script>
                var stripe = Stripe('pk_test_51N07WbDBkL7VmWPMftp4D55jM66LKElXekwmHAb03M1hQzXqVPp7sxuq7Y1hER0Rn9q9qbFtlkJ8FDMKuWXGULJG00bL8RnHLt');
                stripe.redirectToCheckout({
                    sessionId: '{{ session_id }}'
                }).then(function (result) {
                    // Handle any errors from redirecting to Checkout
                });
            </script>

        </div>
    </div>
    {% endblock %}

web_project/templates/UWEFlix/personal_receipts.html
{% extends 'UWEFlix/layout.html' %}

{% block content %}
<h1>My Personal Receipts</h1>

{% if receipts %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Date of Purchase</th>
                <th>Showing</th>
                <th>Adult Tickets</th>
                <th>Student Tickets</th>
                <th>Child Tickets</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            {% for receipt in receipts %}
            <tr>
                <td>{{ receipt.date }}</td>
                <td>{{ receipt.showing.film.title }} on {{ receipt.showing.date }}</td>
                <td>{{ receipt.adult_tickets }}</td>
                <td>{{ receipt.student_tickets }}</td>
                <td>{{ receipt.child_tickets }}</td>
                <td>£{{ receipt.price }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>No personal receipts available.</p>
{% endif %}
{% endblock %}

web_project/templates/UWEFlix/profile.html
{% extends 'UWEFlix/layout.html' %}

{% block content %}
<div class="row justify-content-center mt-5">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                <h1 class="card-title">Profile</h1>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_email">Email address:</label>
                        <input type="email" class="form-control" id="id_email" name="email" value="{{ user.email }}"
                            required>
                    </div>
                    <div class="form-group">
                        <label for="id_first_name">First name:</label>
                        <input type="text" class="form-control" id="id_first_name" name="first_name"
                            value="{{ user.first_name }}" required>
                    </div>
                    <div class="form-group">
                        <label for="id_last_name">Last name:</label>
                        <input type="text" class="form-control" id="id_last_name" name="last_name"
                            value="{{ user.last_name }}" required>
                    </div>
                    <div class="form-group">
                        <label for="id_password">New password:</label>
                        <input type="password" class="form-control" id="id_password" name="password">
                    </div>
                    <div class="form-group">
                        <label for="id_password_confirm">Confirm new password:</label>
                        <input type="password" class="form-control" id="id_password_confirm" name="password_confirm">
                    </div>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </form>
            </div>
            <div class="card-footer text-muted">
                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete
                    Account</button>
            </div>
        </div>
    </div>
</div>

<!-- Delete Account Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Confirm Deletion</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete your account? This action cannot be undone.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <form method="post" action="{% url 'delete_account' %}">
                    {% csrf_token %}
                    <input type="hidden" name="delete_account" value="true">
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

web_project/templates/UWEFlix/purchased_bookings.html
{% extends 'UWEFlix/layout.html' %}

{% block content %}
<div class="container">
    <h1>My Showings</h1>
    {% if bookings %}
        <table class="table">
            <thead>
                <tr>
                    <th>Film</th>
                    <th>Showing</th>
                    <th>Adult Tickets</th>
                    <th>Student Tickets</th>
                    <th>Child Tickets</th>
                    <th>Screen Number</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for booking in bookings %}
                    <tr>
                        <td>{{ booking.showing.film.title }}</td>
                        <td>{{ booking.showing.date }}</td>
                        <td>{{ booking.adult_tickets }}</td>
                        <td>{{ booking.student_tickets }}</td>
                        <td>{{ booking.child_tickets }}</td>
                        <td>{{ booking.showing.screen.number }}</td>
                        <td>
                            <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#cancelModal{{ booking.id }}">Cancel</button>
                        </td>
                    </tr>
                    <!-- Cancel Modal -->
                    <div class="modal fade" id="cancelModal{{ booking.id }}" tabindex="-1" aria-labelledby="cancelModalLabel{{ booking.id }}" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="cancelModalLabel{{ booking.id }}">Request to Cancel Booking</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Are you sure you want to send a cancel request for this booking?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    <a href="{% url 'confirm_delete' booking.id %}" class="btn btn-danger">Confirm Request</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- End Cancel Modal -->
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>You have no bookings coming up.</p>
    {% endif %}
</div>
{% endblock %}

web_project/templates/UWEFlix/statement_detail.html
{% extends 'UWEFlix/layout.html' %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-lg-8">
        <div class="card mb-5">
            <div class="card-header">
                <h1 class="card-title">Statement for {{ statement.account.club.name }} ({{ statement.startdate }} - {{ statement.enddate }})</h1>
            </div>
            <div class="card-body">
                <h2>Receipts</h2>
                <ul class="list-group mb-3">
                    {% for receipt in receipts %}
                    <li class="list-group-item">{{ receipt.date }} - {{ receipt.showing }} - Adult tickets: {{
                        receipt.adult_tickets }} - Student tickets: {{ receipt.student_tickets }} - Child tickets: {{
                        receipt.child_tickets }} - Price: £{{ receipt.price }}</li>
                    {% empty %}
                    <li class="list-group-item">No receipts available.</li>
                    {% endfor %}
                </ul>
                <h2>Club Receipts</h2>
                <ul class="list-group">
                    {% for club_receipt in club_receipts %}
                    <li class="list-group-item">{{ club_receipt.datetime }} - Price: £{{ club_receipt.price }}</li>
                    {% empty %}
                    <li class="list-group-item">No club receipts available.</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

web_project/templates/UWEFlix/updatefilm.html
{% extends "UWEFlix/layout.html" %}

{% block content %}

<div class="container mt-5">
    <h1 class="text-center mb-4">Edit Film Details</h1>
    <form method="post" action="">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label for="{{ form.age_rating.id_for_label }}">{{ form.age_rating.label }}</label>
            {{ form.age_rating }}
        </div>
        <div class="form-group">
            <label for="{{ form.duration.id_for_label }}">{{ form.duration.label }}</label>
            {{ form.duration }}
        </div>
        <div class="form-group">
            <label for="{{ form.trailer_description.id_for_label }}">{{ form.trailer_description.label }}</label>
            {{ form.trailer_description }}
        </div>
        <div class="form-group">
            <label for="{{ form.imageurl.id_for_label }}">{{ form.imageurl.label }}</label>
            {{ form.imageurl }}
        </div>
        <div class="text-center">
            <input type="submit" class="btn btn-primary" value="Save Changes">
        </div>
    </form>
</div>
{% endblock %}